### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by volodya2000** [volodya2000/homepage#5]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.Зробити його *привабливим*.

**Comment by volodymyr-zhuk** [comment]
Hello! My name is Volodymyr and I am a student. I have small  experience in web development and seek to be good at java programming  (and not only in it ) . I want to learn more about developers work and improve my professional knowledge.
