### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by volodya2000** [volodya2000/homepage#6]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Але не вказувати домашні адреси :)

**Comment by volodymyr-zhuk** [comment]
Here is my contact information :
Telegram : @volorymyr_zhuk
Email : volodymyr.zhuk.gp@gmail.com
Github : @volodya2000
