### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by volodya2000** [volodya2000/homepage#7]
Створити список #важливих# подій,досягнень.Також додати отриманий досвід (поганий чи хороший)Список повинен бути впорядкованим.

**Comment by volodymyr-zhuk** [comment]
1. 23.06.2000 - was born
2. 01.09.2006 - went to school
3. ~03.2007 - won my first swimming competition
4. ~ 10.2013 - knew some basics knowledge about Pascal (it was incredible ^_^ )
5.  10.08.2016 - took the third place in the Ukrainian rowing competition
6. 01.09.2017- Enrolled in KPI in the specialty of system analysis
7. 15.07.2019 - Started to learn Java programming language

**Comment by volodymyr-zhuk** [comment]
8 ~ 10.2020 - started to learn Spring Framework.
9. 15.03.2020 - finished my first web [java pet-project](https://github.com/volodya2000/free_BlogServlet). Wrote it using Java EE Servlets. 
My professional skills are: 
1.Backend: Java (Java Core, Java Servlets ,JDBC , Hibernate).
2. Frontend : HTML. CSS,Bootstrap.

**Comment by volodya2000** [comment]
Uhh,sorry, I forgot about some essential events :/ 
Here they are: 
1.11.2018 Took the third place in olympiad in mathematics.
