### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by volodya2000** [volodya2000/homepage#8]
Потрібно додати додаткову інформацію що подобається чи не подобається клієнту , його сильні чи слабкі сторони , навички та хоббі.

**Comment by volodymyr-zhuk** [comment]
Also I like reading ukranian historical books.
My favorite hobbies are: swimming and rowing. 
In my free time i like playing chess.

**Comment by volodya2000** [comment]
I don`t like:
Smoking,eating a lot of fast food,long films.
